name: alexdoctor
favicon: null
layout_spectrum: 0.74897606135346
typography_spectrum: 0.9103566894773394
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.11868816567584872
  lightness: 0.9457619083113968
  saturation: 0.8142978746909648
  rhythmicContrast: 0.6985892769880593
purpose: []
